### ISSUE TITLE
Duplicate item entries

### ISSUE THREAD

**Issue by AgentWill** [cinnamennen/armortracker#25]
In both the inventory and the missing page, some items show up multiple times, with the noticeable ones I saw being Giant Brightbloom Seed (also under the name Giant Brightbloom Seeds), Ice-Breath Lizalfos Tail (also under the name Ice-Breath Lizal Tail), Light Dragon's Talon (also under the name Light Dragon's Claw), and Light Dragon's Fang (also under the name Shard of Light Dragon's Fang).

Basically, it just seems that material names aren't written the same for every recipe, creating a situation where items will appear multiple times, messing up inventory and thus missing counts.

**Comment by cinnamennen** [comment]
Thanks, this should be fixed now!
