### ISSUE TITLE
Would an option for single-screen tracking be possible?

### ISSUE THREAD

**Issue by AtomTheHobkin** [cinnamennen/armortracker#51]
For context, when I played BotW, I used [Volv's Armor Tracker](http://www.volv.org/zelda/) to keep track of how many materials I needed, and for what armor I needed it for. It was all compact, and you could easily track what levels of gear on each set you had done. I absolutely loved it!

I only have a couple issues currently, and they're minor. The rest of the tracker looks amazing though!
- The method of tracking material count is useful, but not practical, given how often you gather materials, and how vast the material list is. An option to remove the count of materials you have would be nice, but isn't a biggie.
- The view is way too spread out, even with the page at 50% zoom, I can only get two armor sets and three rows of materials visible. While the images of the materials is very nice (especially for unfamiliar materials), having it set up in a similar way to Volv's tracker would work much better on the eyes.
- Additionally, maybe the locations of armor pieces would be good, too, if you happen to be missing a few pieces? A quick text guide, or a pinpoint on the map, or the visual location of a cave, or a mix could all do.

I would be greatly happy to see a compact UI for this tracker, whether it be a toggle or not.

_(Note, Volv's tracker doesn't appear to fully work due to lack of pictures, you may have to use the Wayback Machine to fully see)_

**Comment by cinnamennen** [comment]
I think an option for a more compact view and to hide finished armor/materials could be doable. Adding information for where armor is located is a bit out of scope for what I envision for this project. TBH lots of other places have that information and can do a better job with that.
