### ISSUE TITLE
Champions Leathers - First Upgrade

### ISSUE THREAD

**Issue by dunkie12** [cinnamennen/armortracker#61]
Hi there, Firstly - thank you for the page, I'm absolutely loving it!

I see that you have the first upgrade on Champions leathers showing as needing 2x Light Dragon's Talons and 3 Silent Princess.
My game is showing me that it actually needs 2 light dragon's scales and 3 silent princess, please see the attached photo.
Game version is 1.2.0.
![champions leathers upgrade level 1](https://github.com/cinnamennen/armortracker/assets/123528888/cc6a0e8b-e34a-48b2-b8cd-68f5c43ee059)
Thanks!

**Comment by dunkie12** [comment]
In addition -
Now that I've farmed the first upgrade, I've now gotten to the second upgrade and found that the second one is also incorrect.
You have it listed as 2 shards of Light Dragon's Fang, 5 silent princess and 15 sundelion. It's actually 2 shards of Light Dragon's Talon, 3 silent Princess and 10 Sundelion.

**Comment by dunkie12** [comment]
Now I'm up to upgrade number 3 -
You have it listed as 10 Silent Princess, 2 shard of light dragon's horn and 20 sundelion.
The recipe is 5 silent princess, 2 shard of light dragon's fang and 15 sundelion.

**Comment by cinnamennen** [comment]
Can you provide a screenshot of where you are seeing this, e.g. for level 1 upgrade of champion's leathers you are saying the app informs that you need talons when you actually need scales. I think based on what you are saying you are actually using the app slightly incorrectly and have input the level of your armor off by one level.

**Comment by dunkie12** [comment]
Hi there,

Please accept my apology, I must have clicked the first upgrade tier by mistake and had been looking at it all along.
Now that I've gone back and looked at it again I can see all the recipes are correct!
Sorry about that!
I used the rest of them without issues! Haha

Thanks for the awesome site!
